server:
  port: 8001

spring:
  application:
    name: bookstore-book-center
  datasource: 
    book-center: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/book-ms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 'root'
      initial-size: 5
      min-idle: 5
      max-active: 30
      max-wait: 6000
      test-while-idle: true
      validation-query: 'select 1 from dual'
      connect-timeout: 1500
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    
feign:
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      
from: dev-environment-1.0...
